# Use locally available node:20-alpine3.20 image as base to avoid pull failure due to keychain
FROM node:20-alpine3.20

RUN apk add --no-cache caddy

CMD ["caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]
