export { default as ActivityFeedWidget } from './ActivityFeedWidget';
export { default as CaseSummaryWidget } from './CaseSummaryWidget';
export { default as DashboardCustomizer } from './DashboardCustomizer';
export { KPI_LABELS, defaultDashboardSettings } from './types';
export type { DashboardSettings, KpiKey } from './types';
export { default as DonationSummaryWidget } from './DonationSummaryWidget';
export { default as DonationTrendsWidget } from './DonationTrendsWidget';
export { default as EngagementChart } from './EngagementChart';
export { default as EventAttendanceWidget } from './EventAttendanceWidget';
export { default as KPICard } from './KPICard';
export { default as KPISection } from './KPISection';
export { default as ModulesGrid } from './ModulesGrid';
export { default as MyCasesWidget } from './MyCasesWidget';
export { default as PlausibleStatsWidget } from './PlausibleStatsWidget';
export { default as PriorityCards } from './PriorityCards';
export { default as QuickActionsWidget } from './QuickActionsWidget';
export { default as QuickLookupWidget } from './QuickLookupWidget';
export { useQuickLookup, highlightMatch } from './useQuickLookup';
export type { SearchResult, UseQuickLookupOptions } from './useQuickLookup';
export { default as RecentDonationsWidget } from './RecentDonationsWidget';
export { default as UpcomingFollowUpsWidget } from './UpcomingFollowUpsWidget';
export { default as VolunteerHoursWidget } from './VolunteerHoursWidget';
export { default as WidgetContainer } from './WidgetContainer';
