export {
  fetchContactById,
  clearCurrentContact,
  fetchContactNotes,
  createContactNote,
  updateContactNote,
  deleteContactNote,
  fetchContactPhones,
  createContactPhone,
  updateContactPhone,
  deleteContactPhone,
  fetchContactEmails,
  createContactEmail,
  updateContactEmail,
  deleteContactEmail,
  fetchContactRelationships,
  createContactRelationship,
  updateContactRelationship,
  deleteContactRelationship,
  fetchContactDocuments,
  uploadContactDocument,
  updateContactDocument,
  deleteContactDocument,
} from './contactsLegacyCore';
