import type { RouteCatalogEntry } from './types';
import { portalPublicRoute, publicRoute } from './shared';

export const publicRouteCatalogEntries: readonly RouteCatalogEntry[] = [
  publicRoute({
    id: 'root',
    title: 'Workspace Redirect',
    section: 'Core',
    path: '/',
  }),
  publicRoute({
    id: 'setup',
    title: 'Workspace Setup',
    section: 'Auth',
    path: '/setup',
    primaryAction: { label: 'Create admin account', href: '/setup' },
  }),
  publicRoute({
    id: 'login',
    title: 'Sign In',
    section: 'Auth',
    path: '/login',
    primaryAction: { label: 'Sign in', href: '/login' },
  }),
  publicRoute({
    id: 'register',
    title: 'Register',
    section: 'Auth',
    path: '/register',
    primaryAction: { label: 'Create account', href: '/register' },
  }),
  publicRoute({
    id: 'accept-invitation',
    title: 'Accept Invitation',
    section: 'Auth',
    path: '/accept-invitation/:token',
    auditFixtureKey: 'staff-invitation',
    primaryAction: { label: 'Create account', href: '/accept-invitation/:token' },
  }),
  publicRoute({
    id: 'admin-registration-review',
    title: 'Registration Review',
    section: 'Auth',
    path: '/admin-registration-review/:token',
    auditFixtureKey: 'admin-registration-review',
    primaryAction: { label: 'Open approvals', href: '/settings/admin/approvals' },
  }),
  publicRoute({
    id: 'forgot-password',
    title: 'Forgot Password',
    section: 'Auth',
    path: '/forgot-password',
    primaryAction: { label: 'Send reset link', href: '/forgot-password' },
  }),
  publicRoute({
    id: 'reset-password',
    title: 'Reset Password',
    section: 'Auth',
    path: '/reset-password/:token',
    auditFixtureKey: 'password-reset',
    primaryAction: { label: 'Reset password', href: '/reset-password/:token' },
  }),
  publicRoute({
    id: 'public-report-snapshot',
    title: 'Public Report Snapshot',
    section: 'Auth',
    path: '/public/reports/:token',
    auditFixtureKey: 'public-report-snapshot',
  }),
  publicRoute({
    id: 'public-case-form',
    title: 'Public Case Form',
    section: 'Auth',
    path: '/public/case-forms/:token',
    auditFixtureKey: 'public-case-form',
  }),
  publicRoute({
    id: 'public-events',
    title: 'Public Events',
    section: 'Builder',
    path: '/public/events/:site',
    auditFixtureKey: 'public-events',
  }),
  publicRoute({
    id: 'public-event-check-in',
    title: 'Public Event Check-In',
    section: 'Builder',
    path: '/event-check-in/:id',
  }),
  publicRoute({
    id: 'recurring-donation-checkout-result',
    title: 'Monthly Donation Checkout',
    section: 'Builder',
    path: '/recurring-donations/checkout-result',
  }),
  portalPublicRoute({
    id: 'portal-login',
    title: 'Portal Login',
    path: '/portal/login',
    primaryAction: { label: 'Sign in', href: '/portal/login' },
  }),
  portalPublicRoute({
    id: 'portal-signup',
    title: 'Portal Signup',
    path: '/portal/signup',
    primaryAction: { label: 'Submit request', href: '/portal/signup' },
  }),
  portalPublicRoute({
    id: 'portal-forgot-password',
    title: 'Portal Forgot Password',
    path: '/portal/forgot-password',
    primaryAction: { label: 'Send reset link', href: '/portal/forgot-password' },
  }),
  portalPublicRoute({
    id: 'portal-reset-password',
    title: 'Portal Reset Password',
    path: '/portal/reset-password/:token',
    auditFixtureKey: 'portal-password-reset',
    primaryAction: { label: 'Reset password', href: '/portal/reset-password/:token' },
  }),
  portalPublicRoute({
    id: 'portal-accept-invitation',
    title: 'Portal Invitation',
    path: '/portal/accept-invitation/:token',
    auditFixtureKey: 'portal-invitation',
    primaryAction: {
      label: 'Activate portal account',
      href: '/portal/accept-invitation/:token',
    },
  }),
];
