import type { RouteCatalogEntry } from './types';
import { adminRoute, settingsRoute, staffRoute } from './shared';
import { getAdminRouteMeta } from './staffAdminRouteMeta';

export const staffAdminRouteCatalogEntries: readonly RouteCatalogEntry[] = [
  staffRoute({
    id: 'intake-create',
    title: 'New Intake',
    section: 'Core',
    path: '/intake/new',
    primaryAction: { label: 'Create contact', href: '/intake/new' },
  }),
  staffRoute({
    id: 'interaction-create',
    title: 'Note an Interaction',
    section: 'Core',
    path: '/interactions/new',
    primaryAction: { label: 'Create new person', href: '/contacts/new' },
  }),
  staffRoute({
    id: 'people-directory',
    title: 'People Directory',
    section: 'Core',
    path: '/people',
  }),
  staffRoute({
    id: 'linking',
    title: 'Linking',
    section: 'Core',
    path: '/linking',
  }),
  staffRoute({
    id: 'operations',
    title: 'Operations',
    section: 'Core',
    path: '/operations',
  }),
  staffRoute({
    id: 'outreach',
    title: 'Outreach',
    section: 'Core',
    path: '/outreach',
  }),
  settingsRoute({
    id: 'user-settings',
    title: 'User Settings',
    path: '/settings/user',
    featureStatus: 'available',
  }),
  adminRoute({
    id: 'admin-settings',
    title: getAdminRouteMeta('admin-settings').title,
    path: getAdminRouteMeta('admin-settings').path,
    adminSurface: getAdminRouteMeta('admin-settings').surface,
    adminLabel: getAdminRouteMeta('admin-settings').label,
    adminDescription: getAdminRouteMeta('admin-settings').description,
    adminIcon: getAdminRouteMeta('admin-settings').icon,
    adminNav:
      getAdminRouteMeta('admin-settings').surface === 'core'
        ? [
            { mode: 'settings', order: 10, label: 'Admin Hub' },
            { mode: 'portal', order: 10, label: 'Admin Hub' },
          ]
        : undefined,
  }),
  adminRoute({
    id: 'admin-settings-approvals',
    title: getAdminRouteMeta('admin-settings-approvals').title,
    path: getAdminRouteMeta('admin-settings-approvals').path,
    adminSurface: getAdminRouteMeta('admin-settings-approvals').surface,
    adminLabel: getAdminRouteMeta('admin-settings-approvals').label,
    adminDescription: getAdminRouteMeta('admin-settings-approvals').description,
    adminIcon: getAdminRouteMeta('admin-settings-approvals').icon,
  }),
  adminRoute({
    id: 'admin-settings-organization',
    title: getAdminRouteMeta('admin-settings-organization').title,
    path: getAdminRouteMeta('admin-settings-organization').path,
    adminSurface: getAdminRouteMeta('admin-settings-organization').surface,
    adminLabel: getAdminRouteMeta('admin-settings-organization').label,
    adminDescription: getAdminRouteMeta('admin-settings-organization').description,
    adminIcon: getAdminRouteMeta('admin-settings-organization').icon,
  }),
  adminRoute({
    id: 'admin-settings-workspace-modules',
    title: getAdminRouteMeta('admin-settings-workspace-modules').title,
    path: getAdminRouteMeta('admin-settings-workspace-modules').path,
    adminSurface: getAdminRouteMeta('admin-settings-workspace-modules').surface,
    adminLabel: getAdminRouteMeta('admin-settings-workspace-modules').label,
    adminDescription: getAdminRouteMeta('admin-settings-workspace-modules').description,
    adminIcon: getAdminRouteMeta('admin-settings-workspace-modules').icon,
  }),
  adminRoute({
    id: 'admin-settings-branding',
    title: getAdminRouteMeta('admin-settings-branding').title,
    path: getAdminRouteMeta('admin-settings-branding').path,
    adminSurface: getAdminRouteMeta('admin-settings-branding').surface,
    adminLabel: getAdminRouteMeta('admin-settings-branding').label,
    adminDescription: getAdminRouteMeta('admin-settings-branding').description,
    adminIcon: getAdminRouteMeta('admin-settings-branding').icon,
  }),
  adminRoute({
    id: 'admin-settings-users',
    title: getAdminRouteMeta('admin-settings-users').title,
    path: getAdminRouteMeta('admin-settings-users').path,
    adminSurface: getAdminRouteMeta('admin-settings-users').surface,
    adminLabel: getAdminRouteMeta('admin-settings-users').label,
    adminDescription: getAdminRouteMeta('admin-settings-users').description,
    adminIcon: getAdminRouteMeta('admin-settings-users').icon,
  }),
  adminRoute({
    id: 'admin-settings-groups',
    title: getAdminRouteMeta('admin-settings-groups').title,
    path: getAdminRouteMeta('admin-settings-groups').path,
    adminSurface: getAdminRouteMeta('admin-settings-groups').surface,
    adminLabel: getAdminRouteMeta('admin-settings-groups').label,
    adminDescription: getAdminRouteMeta('admin-settings-groups').description,
    adminIcon: getAdminRouteMeta('admin-settings-groups').icon,
  }),
  adminRoute({
    id: 'admin-settings-communications',
    title: getAdminRouteMeta('admin-settings-communications').title,
    path: getAdminRouteMeta('admin-settings-communications').path,
    adminSurface: getAdminRouteMeta('admin-settings-communications').surface,
    adminLabel: getAdminRouteMeta('admin-settings-communications').label,
    adminDescription: getAdminRouteMeta('admin-settings-communications').description,
    adminIcon: getAdminRouteMeta('admin-settings-communications').icon,
  }),
  adminRoute({
    id: 'admin-settings-messaging',
    title: getAdminRouteMeta('admin-settings-messaging').title,
    path: getAdminRouteMeta('admin-settings-messaging').path,
    adminSurface: getAdminRouteMeta('admin-settings-messaging').surface,
    adminLabel: getAdminRouteMeta('admin-settings-messaging').label,
    adminDescription: getAdminRouteMeta('admin-settings-messaging').description,
    adminIcon: getAdminRouteMeta('admin-settings-messaging').icon,
  }),
  adminRoute({
    id: 'admin-settings-outcomes',
    title: getAdminRouteMeta('admin-settings-outcomes').title,
    path: getAdminRouteMeta('admin-settings-outcomes').path,
    adminSurface: getAdminRouteMeta('admin-settings-outcomes').surface,
    adminLabel: getAdminRouteMeta('admin-settings-outcomes').label,
    adminDescription: getAdminRouteMeta('admin-settings-outcomes').description,
    adminIcon: getAdminRouteMeta('admin-settings-outcomes').icon,
  }),
  adminRoute({
    id: 'admin-settings-roles',
    title: getAdminRouteMeta('admin-settings-roles').title,
    path: getAdminRouteMeta('admin-settings-roles').path,
    adminSurface: getAdminRouteMeta('admin-settings-roles').surface,
    adminLabel: getAdminRouteMeta('admin-settings-roles').label,
    adminDescription: getAdminRouteMeta('admin-settings-roles').description,
    adminIcon: getAdminRouteMeta('admin-settings-roles').icon,
  }),
  adminRoute({
    id: 'admin-settings-audit-logs',
    title: getAdminRouteMeta('admin-settings-audit-logs').title,
    path: getAdminRouteMeta('admin-settings-audit-logs').path,
    adminSurface: getAdminRouteMeta('admin-settings-audit-logs').surface,
    adminLabel: getAdminRouteMeta('admin-settings-audit-logs').label,
    adminDescription: getAdminRouteMeta('admin-settings-audit-logs').description,
    adminIcon: getAdminRouteMeta('admin-settings-audit-logs').icon,
  }),
  adminRoute({
    id: 'admin-settings-other',
    title: getAdminRouteMeta('admin-settings-other').title,
    path: getAdminRouteMeta('admin-settings-other').path,
    adminSurface: getAdminRouteMeta('admin-settings-other').surface,
    adminLabel: getAdminRouteMeta('admin-settings-other').label,
    adminDescription: getAdminRouteMeta('admin-settings-other').description,
    adminIcon: getAdminRouteMeta('admin-settings-other').icon,
  }),
  settingsRoute({
    id: 'api-settings',
    title: getAdminRouteMeta('api-settings').title,
    path: getAdminRouteMeta('api-settings').path,
    adminSurface: getAdminRouteMeta('api-settings').surface,
    adminLabel: getAdminRouteMeta('api-settings').title,
    adminDescription: getAdminRouteMeta('api-settings').description,
    adminIcon: getAdminRouteMeta('api-settings').icon,
    adminNav: { mode: 'settings', order: 120, label: getAdminRouteMeta('api-settings').title },
    featureStatus: 'available',
    showInMobileDrawerUtilities: true,
  }),
  settingsRoute({
    id: 'navigation-settings',
    title: getAdminRouteMeta('navigation-settings').title,
    path: getAdminRouteMeta('navigation-settings').path,
    adminSurface: getAdminRouteMeta('navigation-settings').surface,
    adminLabel: getAdminRouteMeta('navigation-settings').title,
    adminDescription: getAdminRouteMeta('navigation-settings').description,
    adminIcon: getAdminRouteMeta('navigation-settings').icon,
    adminNav: { mode: 'settings', order: 130, label: 'Navigation' },
    featureStatus: 'available',
    showInMobileDrawerUtilities: true,
  }),
  adminRoute({
    id: 'backup-settings',
    title: getAdminRouteMeta('backup-settings').title,
    path: getAdminRouteMeta('backup-settings').path,
    adminSurface: getAdminRouteMeta('backup-settings').surface,
    adminLabel: getAdminRouteMeta('backup-settings').title,
    adminDescription: getAdminRouteMeta('backup-settings').description,
    adminIcon: getAdminRouteMeta('backup-settings').icon,
    adminNav: { mode: 'settings', order: 140, label: getAdminRouteMeta('backup-settings').title },
  }),
  settingsRoute({
    id: 'communications',
    title: getAdminRouteMeta('communications').title,
    path: getAdminRouteMeta('communications').path,
    adminSurface: getAdminRouteMeta('communications').surface,
    adminLabel: getAdminRouteMeta('communications').title,
    adminDescription: getAdminRouteMeta('communications').description,
    adminIcon: getAdminRouteMeta('communications').icon,
    adminNav: {
      mode: 'settings',
      order: 150,
      label: getAdminRouteMeta('communications').title,
      matchPrefixes: ['/settings/email-marketing'],
    },
    featureStatus: 'available',
  }),
  settingsRoute({
    id: 'email-marketing',
    title: 'Newsletter Campaigns',
    path: '/settings/email-marketing',
    parentId: 'communications',
    featureStatus: 'available',
  }),
  adminRoute({
    id: 'social-media',
    title: getAdminRouteMeta('social-media').title,
    path: getAdminRouteMeta('social-media').path,
    adminSurface: getAdminRouteMeta('social-media').surface,
    adminLabel: getAdminRouteMeta('social-media').title,
    adminDescription: getAdminRouteMeta('social-media').description,
    adminIcon: getAdminRouteMeta('social-media').icon,
    adminNav: { mode: 'settings', order: 160, label: getAdminRouteMeta('social-media').title },
    featureStatus: 'available',
  }),
  adminRoute({
    id: 'portal-admin-access',
    title: getAdminRouteMeta('portal-admin-access').title,
    path: getAdminRouteMeta('portal-admin-access').path,
    adminSurface: getAdminRouteMeta('portal-admin-access').surface,
    adminLabel: getAdminRouteMeta('portal-admin-access').title,
    adminDescription: getAdminRouteMeta('portal-admin-access').description,
    adminIcon: getAdminRouteMeta('portal-admin-access').icon,
    adminNav: [
      {
        mode: 'settings',
        order: 110,
        label: getAdminRouteMeta('portal-admin-access').title,
        matchPrefixes: ['/settings/admin/portal'],
      },
      {
        mode: 'portal',
        order: 20,
        label: 'Access',
      },
    ],
  }),
  adminRoute({
    id: 'portal-admin-users',
    title: getAdminRouteMeta('portal-admin-users').title,
    path: getAdminRouteMeta('portal-admin-users').path,
    adminSurface: getAdminRouteMeta('portal-admin-users').surface,
    adminLabel: getAdminRouteMeta('portal-admin-users').title,
    adminDescription: getAdminRouteMeta('portal-admin-users').description,
    adminIcon: getAdminRouteMeta('portal-admin-users').icon,
    adminNav: { mode: 'portal', order: 30, label: 'Users' },
  }),
  adminRoute({
    id: 'portal-admin-conversations',
    title: getAdminRouteMeta('portal-admin-conversations').title,
    path: getAdminRouteMeta('portal-admin-conversations').path,
    adminSurface: getAdminRouteMeta('portal-admin-conversations').surface,
    adminLabel: getAdminRouteMeta('portal-admin-conversations').title,
    adminDescription: getAdminRouteMeta('portal-admin-conversations').description,
    adminIcon: getAdminRouteMeta('portal-admin-conversations').icon,
    adminNav: { mode: 'portal', order: 40, label: 'Conversations' },
  }),
  adminRoute({
    id: 'portal-admin-appointments',
    title: getAdminRouteMeta('portal-admin-appointments').title,
    path: getAdminRouteMeta('portal-admin-appointments').path,
    adminSurface: getAdminRouteMeta('portal-admin-appointments').surface,
    adminLabel: getAdminRouteMeta('portal-admin-appointments').title,
    adminDescription: getAdminRouteMeta('portal-admin-appointments').description,
    adminIcon: getAdminRouteMeta('portal-admin-appointments').icon,
    adminNav: { mode: 'portal', order: 50, label: 'Appointments' },
  }),
  adminRoute({
    id: 'portal-admin-slots',
    title: getAdminRouteMeta('portal-admin-slots').title,
    path: getAdminRouteMeta('portal-admin-slots').path,
    adminSurface: getAdminRouteMeta('portal-admin-slots').surface,
    adminLabel: getAdminRouteMeta('portal-admin-slots').title,
    adminDescription: getAdminRouteMeta('portal-admin-slots').description,
    adminIcon: getAdminRouteMeta('portal-admin-slots').icon,
    adminNav: { mode: 'portal', order: 60, label: 'Slots' },
  }),
];
