import type { RouteCatalogEntry } from './types';
import { staffRoute } from './shared';

export const staffFinanceRouteCatalogEntries: readonly RouteCatalogEntry[] = [
  staffRoute({
    id: 'donations',
    title: 'Donations',
    section: 'Finance',
    path: '/donations',
    primaryAction: { label: 'Record donation', href: '/donations/new' },
    mobilePriority: 60,
    staffNav: {
      group: 'secondary',
      order: 120,
      label: 'Donations',
      shortLabel: 'Donations',
      ariaLabel: 'Go to donations',
      icon: '💰',
      pinnedEligible: true,
    },
  }),
  staffRoute({
    id: 'donation-create',
    title: 'Record Donation',
    section: 'Finance',
    path: '/donations/new',
  }),
  staffRoute({
    id: 'donation-detail',
    title: 'Donation Detail',
    section: 'Finance',
    path: '/donations/:id',
  }),
  staffRoute({
    id: 'donation-edit',
    title: 'Edit Donation',
    section: 'Finance',
    path: '/donations/:id/edit',
  }),
  staffRoute({
    id: 'donation-payment',
    title: 'Donation Payment',
    section: 'Finance',
    path: '/donations/payment',
  }),
  staffRoute({
    id: 'donation-payment-result',
    title: 'Donation Payment Result',
    section: 'Finance',
    path: '/donations/payment-result',
  }),
  staffRoute({
    id: 'recurring-donations',
    title: 'Recurring Donations',
    section: 'Finance',
    path: '/recurring-donations',
    staffNav: {
      group: 'secondary',
      order: 125,
      label: 'Monthly Plans',
      shortLabel: 'Monthly Plans',
      ariaLabel: 'Go to recurring donations',
      icon: '🔁',
      pinnedEligible: true,
    },
  }),
  staffRoute({
    id: 'recurring-donation-detail',
    title: 'Recurring Donation Detail',
    section: 'Finance',
    path: '/recurring-donations/:id',
  }),
  staffRoute({
    id: 'recurring-donation-edit',
    title: 'Edit Recurring Donation',
    section: 'Finance',
    path: '/recurring-donations/:id/edit',
  }),
  staffRoute({
    id: 'reconciliation',
    title: 'Reconciliation',
    section: 'Finance',
    path: '/reconciliation',
    staffNav: {
      group: 'secondary',
      order: 130,
      label: 'Reconciliation',
      shortLabel: 'Reconciliation',
      ariaLabel: 'Go to reconciliation',
      icon: '🧮',
      pinnedEligible: true,
    },
  }),
  staffRoute({
    id: 'grants',
    title: 'Grants',
    section: 'Finance',
    path: '/grants',
    primaryAction: { label: 'New application', href: '/grants/applications' },
    staffNav: {
      group: 'secondary',
      order: 135,
      label: 'Grants',
      shortLabel: 'Grants',
      ariaLabel: 'Go to grants',
      icon: '🏛️',
      pinnedEligible: true,
    },
  }),
  staffRoute({
    id: 'grants-funders',
    title: 'Grant Funders',
    section: 'Finance',
    path: '/grants/funders',
  }),
  staffRoute({
    id: 'grants-programs',
    title: 'Grant Programs',
    section: 'Finance',
    path: '/grants/programs',
  }),
  staffRoute({
    id: 'grants-recipients',
    title: 'Recipient Organizations',
    section: 'Finance',
    path: '/grants/recipients',
  }),
  staffRoute({
    id: 'grants-funded-programs',
    title: 'Funded Programs',
    section: 'Finance',
    path: '/grants/funded-programs',
  }),
  staffRoute({
    id: 'grants-applications',
    title: 'Grant Applications',
    section: 'Finance',
    path: '/grants/applications',
  }),
  staffRoute({
    id: 'grants-awards',
    title: 'Grant Awards',
    section: 'Finance',
    path: '/grants/awards',
  }),
  staffRoute({
    id: 'grants-disbursements',
    title: 'Grant Disbursements',
    section: 'Finance',
    path: '/grants/disbursements',
  }),
  staffRoute({
    id: 'grants-reports',
    title: 'Grant Reports',
    section: 'Finance',
    path: '/grants/reports',
  }),
  staffRoute({
    id: 'grants-documents',
    title: 'Grant Documents',
    section: 'Finance',
    path: '/grants/documents',
  }),
  staffRoute({
    id: 'grants-calendar',
    title: 'Grant Calendar',
    section: 'Finance',
    path: '/grants/calendar',
  }),
  staffRoute({
    id: 'grants-activities',
    title: 'Grant Activity Log',
    section: 'Finance',
    path: '/grants/activities',
  }),
];

export const staffFinanceRouteCatalogAuditTargets = [
  { path: '/donations' },
  { href: '/donations/new' },
  { path: '/donations/new' },
  { path: '/donations/:id' },
  { path: '/donations/:id/edit' },
  { path: '/donations/payment' },
  { path: '/donations/payment-result' },
  { path: '/recurring-donations' },
  { path: '/recurring-donations/:id' },
  { path: '/recurring-donations/:id/edit' },
  { path: '/reconciliation' },
  { path: '/grants' },
  { href: '/grants/applications' },
  { path: '/grants/funders' },
  { path: '/grants/programs' },
  { path: '/grants/recipients' },
  { path: '/grants/funded-programs' },
  { path: '/grants/applications' },
  { path: '/grants/awards' },
  { path: '/grants/disbursements' },
  { path: '/grants/reports' },
  { path: '/grants/documents' },
  { path: '/grants/calendar' },
  { path: '/grants/activities' },
] as const;
