import type { RouteCatalogEntry } from './types';
import { staffRoute } from './shared';

export const staffInsightsRouteCatalogEntries: readonly RouteCatalogEntry[] = [
  staffRoute({
    id: 'analytics',
    title: 'Analytics',
    section: 'Analytics',
    path: '/analytics',
    primaryAction: { label: 'Apply filters', href: '/analytics' },
    showInMobileDrawerUtilities: true,
    staffNav: {
      group: 'utility',
      order: 140,
      label: 'Analytics',
      shortLabel: 'Analytics',
      ariaLabel: 'Go to analytics',
      icon: '📉',
    },
  }),
  staffRoute({
    id: 'dashboard-custom',
    title: 'Custom Dashboard',
    section: 'Analytics',
    path: '/dashboard/custom',
  }),
  staffRoute({
    id: 'reports',
    title: 'Reports',
    section: 'Analytics',
    path: '/reports',
    href: '/reports',
    primaryAction: { label: 'Open reports', href: '/reports' },
    showInMobileDrawerUtilities: true,
    staffNav: {
      group: 'utility',
      order: 150,
      label: 'Reports',
      shortLabel: 'Reports',
      ariaLabel: 'Go to reports',
      icon: '🗂️',
    },
  }),
  staffRoute({
    id: 'reports-builder',
    title: 'Report Builder',
    section: 'Analytics',
    path: '/reports/builder',
    primaryAction: { label: 'Generate report', href: '/reports/builder' },
  }),
  staffRoute({
    id: 'reports-templates',
    title: 'Report Templates',
    section: 'Analytics',
    path: '/reports/templates',
    primaryAction: { label: 'Create custom report', href: '/reports/builder' },
  }),
  staffRoute({
    id: 'reports-saved',
    title: 'Saved Reports',
    section: 'Analytics',
    path: '/reports/saved',
  }),
  staffRoute({
    id: 'reports-scheduled',
    title: 'Scheduled Reports',
    section: 'Analytics',
    path: '/reports/scheduled',
    staffNav: {
      group: 'secondary',
      order: 160,
      label: 'Scheduled Reports',
      shortLabel: 'Schedules',
      ariaLabel: 'Go to scheduled reports',
      icon: '🗓️',
      pinnedEligible: true,
    },
  }),
  staffRoute({
    id: 'reports-outcomes',
    title: 'Outcomes Report',
    section: 'Analytics',
    path: '/reports/outcomes',
  }),
  staffRoute({
    id: 'reports-workflow-coverage',
    title: 'Workflow Coverage Report',
    section: 'Analytics',
    path: '/reports/workflow-coverage',
  }),
  staffRoute({
    id: 'alerts-overview',
    title: 'Alerts',
    section: 'Analytics',
    path: '/alerts',
    primaryAction: { label: 'Create alert', href: '/alerts' },
    showInMobileHeader: true,
    staffNav: {
      group: 'utility',
      order: 170,
      label: 'Alerts',
      shortLabel: 'Alerts',
      ariaLabel: 'Go to alerts',
      icon: '🚨',
    },
  }),
  staffRoute({
    id: 'alerts-instances',
    title: 'Triggered Alerts',
    section: 'Analytics',
    path: '/alerts/instances',
  }),
  staffRoute({
    id: 'alerts-history',
    title: 'Alert History',
    section: 'Analytics',
    path: '/alerts/history',
  }),
];
