import type { RouteCatalogEntry } from './types';
import { staffRoute } from './shared';

export const staffPeopleRouteCatalogEntries: readonly RouteCatalogEntry[] = [
  staffRoute({
    id: 'contacts',
    title: 'People',
    section: 'People',
    path: '/contacts',
    primaryAction: { label: 'New person', href: '/contacts/new' },
    mobilePriority: 20,
    staffNav: {
      group: 'primary',
      order: 20,
      label: 'People',
      shortLabel: 'People',
      ariaLabel: 'Go to contacts',
      icon: '👤',
      pinnedEligible: true,
    },
  }),
  staffRoute({
    id: 'contact-create',
    title: 'Create Person',
    section: 'People',
    path: '/contacts/new',
    primaryAction: { label: 'Save person', href: '/contacts/new' },
  }),
  staffRoute({
    id: 'contact-detail',
    title: 'Person Detail',
    section: 'People',
    path: '/contacts/:id',
  }),
  staffRoute({
    id: 'contact-edit',
    title: 'Edit Person',
    section: 'People',
    path: '/contacts/:id/edit',
  }),
  staffRoute({
    id: 'contact-print',
    title: 'Print / Export',
    section: 'People',
    path: '/contacts/:id/print',
  }),
  staffRoute({
    id: 'accounts',
    title: 'Accounts',
    section: 'People',
    path: '/accounts',
    primaryAction: { label: 'New account', href: '/accounts/new' },
    staffNav: {
      group: 'secondary',
      order: 30,
      label: 'Accounts',
      shortLabel: 'Accounts',
      ariaLabel: 'Go to accounts',
      icon: '🏢',
      pinnedEligible: true,
    },
  }),
  staffRoute({
    id: 'account-create',
    title: 'Create Account',
    section: 'People',
    path: '/accounts/new',
    primaryAction: { label: 'Save account', href: '/accounts/new' },
  }),
  staffRoute({
    id: 'account-detail',
    title: 'Account Detail',
    section: 'People',
    path: '/accounts/:id',
  }),
  staffRoute({
    id: 'account-edit',
    title: 'Edit Account',
    section: 'People',
    path: '/accounts/:id/edit',
  }),
  staffRoute({
    id: 'volunteers',
    title: 'Volunteers',
    section: 'People',
    path: '/volunteers',
    primaryAction: { label: 'New volunteer', href: '/volunteers/new' },
    staffNav: {
      group: 'secondary',
      order: 40,
      label: 'Volunteers',
      shortLabel: 'Volunteers',
      ariaLabel: 'Go to volunteers',
      icon: '🤝',
      pinnedEligible: true,
    },
  }),
  staffRoute({
    id: 'volunteer-create',
    title: 'Create Volunteer',
    section: 'People',
    path: '/volunteers/new',
    primaryAction: { label: 'Save volunteer', href: '/volunteers/new' },
  }),
  staffRoute({
    id: 'volunteer-detail',
    title: 'Volunteer Detail',
    section: 'People',
    path: '/volunteers/:id',
  }),
  staffRoute({
    id: 'volunteer-edit',
    title: 'Edit Volunteer',
    section: 'People',
    path: '/volunteers/:id/edit',
  }),
  staffRoute({
    id: 'volunteer-assignment-create',
    title: 'Create Assignment',
    section: 'People',
    path: '/volunteers/:volunteerId/assignments/new',
  }),
  staffRoute({
    id: 'volunteer-assignment-edit',
    title: 'Edit Assignment',
    section: 'People',
    path: '/volunteers/:volunteerId/assignments/:assignmentId/edit',
  }),
];

export const staffPeopleRouteCatalogAuditTargets = [
  { path: '/contacts' },
  { href: '/contacts/new' },
  { path: '/contacts/new' },
  { path: '/contacts/:id' },
  { path: '/contacts/:id/edit' },
  { path: '/contacts/:id/print' },
  { path: '/accounts' },
  { href: '/accounts/new' },
  { path: '/accounts/new' },
  { path: '/accounts/:id' },
  { path: '/accounts/:id/edit' },
  { path: '/volunteers' },
  { href: '/volunteers/new' },
  { path: '/volunteers/new' },
  { path: '/volunteers/:id' },
  { path: '/volunteers/:id/edit' },
  { path: '/volunteers/:volunteerId/assignments/new' },
  { path: '/volunteers/:volunteerId/assignments/:assignmentId/edit' },
] as const;
