import type { RouteCatalogEntry } from './types';
import { adminRoute, settingsRoute, staffRoute } from './shared';

export const staffRouteCatalogEntries: readonly RouteCatalogEntry[] = [
  staffRoute({
    id: 'dashboard',
    title: 'Dashboard',
    section: 'Core',
    path: '/dashboard',
    primaryAction: { label: 'Create intake', href: '/intake/new' },
    staffNav: {
      group: 'primary',
      order: 10,
      label: 'Dashboard',
      shortLabel: 'Home',
      ariaLabel: 'Go to dashboard',
      icon: '📊',
    },
  }),
  staffRoute({
    id: 'contacts',
    title: 'People',
    section: 'People',
    path: '/contacts',
    primaryAction: { label: 'New person', href: '/contacts/new' },
    staffNav: {
      group: 'primary',
      order: 20,
      label: 'People',
      shortLabel: 'People',
      ariaLabel: 'Go to contacts',
      icon: '👤',
      pinnedEligible: true,
    },
  }),
  staffRoute({
    id: 'contact-create',
    title: 'Create Person',
    section: 'People',
    path: '/contacts/new',
    primaryAction: { label: 'Save person', href: '/contacts/new' },
  }),
  staffRoute({
    id: 'contact-detail',
    title: 'Person Detail',
    section: 'People',
    path: '/contacts/:id',
  }),
  staffRoute({
    id: 'contact-edit',
    title: 'Edit Person',
    section: 'People',
    path: '/contacts/:id/edit',
  }),
  staffRoute({
    id: 'accounts',
    title: 'Accounts',
    section: 'People',
    path: '/accounts',
    primaryAction: { label: 'New account', href: '/accounts/new' },
    staffNav: {
      group: 'secondary',
      order: 30,
      label: 'Accounts',
      shortLabel: 'Accounts',
      ariaLabel: 'Go to accounts',
      icon: '🏢',
      pinnedEligible: true,
    },
  }),
  staffRoute({
    id: 'account-create',
    title: 'Create Account',
    section: 'People',
    path: '/accounts/new',
    primaryAction: { label: 'Save account', href: '/accounts/new' },
  }),
  staffRoute({
    id: 'account-detail',
    title: 'Account Detail',
    section: 'People',
    path: '/accounts/:id',
  }),
  staffRoute({
    id: 'account-edit',
    title: 'Edit Account',
    section: 'People',
    path: '/accounts/:id/edit',
  }),
  staffRoute({
    id: 'volunteers',
    title: 'Volunteers',
    section: 'People',
    path: '/volunteers',
    primaryAction: { label: 'New volunteer', href: '/volunteers/new' },
    staffNav: {
      group: 'secondary',
      order: 40,
      label: 'Volunteers',
      shortLabel: 'Volunteers',
      ariaLabel: 'Go to volunteers',
      icon: '🤝',
      pinnedEligible: true,
    },
  }),
  staffRoute({
    id: 'volunteer-create',
    title: 'Create Volunteer',
    section: 'People',
    path: '/volunteers/new',
    primaryAction: { label: 'Save volunteer', href: '/volunteers/new' },
  }),
  staffRoute({
    id: 'volunteer-detail',
    title: 'Volunteer Detail',
    section: 'People',
    path: '/volunteers/:id',
  }),
  staffRoute({
    id: 'volunteer-edit',
    title: 'Edit Volunteer',
    section: 'People',
    path: '/volunteers/:id/edit',
  }),
  staffRoute({
    id: 'volunteer-assignment-create',
    title: 'Create Assignment',
    section: 'People',
    path: '/volunteers/:volunteerId/assignments/new',
  }),
  staffRoute({
    id: 'volunteer-assignment-edit',
    title: 'Edit Assignment',
    section: 'People',
    path: '/volunteers/:volunteerId/assignments/:assignmentId/edit',
  }),
  staffRoute({
    id: 'events',
    title: 'Events',
    section: 'Engagement',
    path: '/events',
    primaryAction: { label: 'Create event', href: '/events/new' },
    staffNav: {
      group: 'primary',
      order: 50,
      label: 'Events',
      shortLabel: 'Events',
      ariaLabel: 'Go to events',
      icon: '📅',
      pinnedEligible: true,
    },
  }),
  staffRoute({
    id: 'events-calendar',
    title: 'Event Calendar',
    section: 'Engagement',
    path: '/events/calendar',
  }),
  staffRoute({
    id: 'events-check-in',
    title: 'Event Check-In',
    section: 'Engagement',
    path: '/events/check-in',
  }),
  staffRoute({
    id: 'event-create',
    title: 'Create Event',
    section: 'Engagement',
    path: '/events/new',
    primaryAction: { label: 'Create event', href: '/events/new' },
  }),
  staffRoute({
    id: 'event-detail',
    title: 'Event Detail',
    section: 'Engagement',
    path: '/events/:id',
  }),
  staffRoute({
    id: 'event-edit',
    title: 'Edit Event',
    section: 'Engagement',
    path: '/events/:id/edit',
  }),
  staffRoute({
    id: 'tasks',
    title: 'Tasks',
    section: 'Engagement',
    path: '/tasks',
    primaryAction: { label: 'New task', href: '/tasks/new' },
    staffNav: {
      group: 'primary',
      order: 60,
      label: 'Tasks',
      shortLabel: 'Tasks',
      ariaLabel: 'Go to tasks',
      icon: '✓',
      pinnedEligible: true,
    },
  }),
  staffRoute({
    id: 'task-create',
    title: 'Create Task',
    section: 'Engagement',
    path: '/tasks/new',
    primaryAction: { label: 'Save task', href: '/tasks/new' },
  }),
  staffRoute({
    id: 'task-detail',
    title: 'Task Detail',
    section: 'Engagement',
    path: '/tasks/:id',
  }),
  staffRoute({
    id: 'task-edit',
    title: 'Edit Task',
    section: 'Engagement',
    path: '/tasks/:id/edit',
  }),
  staffRoute({
    id: 'cases',
    title: 'Cases',
    section: 'Engagement',
    path: '/cases',
    primaryAction: { label: 'New case', href: '/cases/new' },
    staffNav: {
      group: 'primary',
      order: 70,
      label: 'Cases',
      shortLabel: 'Cases',
      ariaLabel: 'Go to cases',
      icon: '📋',
      pinnedEligible: true,
    },
  }),
  staffRoute({
    id: 'case-create',
    title: 'Create Case',
    section: 'Engagement',
    path: '/cases/new',
    primaryAction: { label: 'Save case', href: '/cases/new' },
  }),
  staffRoute({
    id: 'case-detail',
    title: 'Case Detail',
    section: 'Engagement',
    path: '/cases/:id',
  }),
  staffRoute({
    id: 'case-edit',
    title: 'Edit Case',
    section: 'Engagement',
    path: '/cases/:id/edit',
  }),
  staffRoute({
    id: 'follow-ups',
    title: 'Follow-Ups',
    section: 'Engagement',
    path: '/follow-ups',
    primaryAction: { label: 'Create follow-up', href: '/follow-ups' },
    staffNav: {
      group: 'secondary',
      order: 80,
      label: 'Follow-Ups',
      shortLabel: 'Follow-ups',
      ariaLabel: 'Go to follow-ups',
      icon: '🔔',
      pinnedEligible: true,
    },
  }),
  staffRoute({
    id: 'opportunities',
    title: 'Opportunities',
    section: 'Engagement',
    path: '/opportunities',
    primaryAction: { label: 'New opportunity', href: '/opportunities' },
    staffNav: {
      group: 'secondary',
      order: 90,
      label: 'Opportunities',
      shortLabel: 'Pipeline',
      ariaLabel: 'Go to opportunities',
      icon: '📈',
      pinnedEligible: true,
    },
  }),
  staffRoute({
    id: 'external-service-providers',
    title: 'External Service Providers',
    section: 'Engagement',
    path: '/external-service-providers',
    staffNav: {
      group: 'secondary',
      order: 100,
      label: 'Providers',
      shortLabel: 'Providers',
      ariaLabel: 'Go to external service providers',
      icon: '🩺',
      pinnedEligible: true,
    },
  }),
  staffRoute({
    id: 'team-chat',
    title: 'Team Messenger',
    section: 'Engagement',
    path: '/team-chat',
    featureFlagEnv: 'VITE_TEAM_CHAT_ENABLED',
    staffNav: {
      group: 'secondary',
      order: 110,
      label: 'Team Messenger',
      shortLabel: 'Messenger',
      ariaLabel: 'Go to team messenger',
      icon: '💬',
      pinnedEligible: true,
    },
  }),
  staffRoute({
    id: 'donations',
    title: 'Donations',
    section: 'Finance',
    path: '/donations',
    primaryAction: { label: 'Record donation', href: '/donations/new' },
    staffNav: {
      group: 'secondary',
      order: 120,
      label: 'Donations',
      shortLabel: 'Donations',
      ariaLabel: 'Go to donations',
      icon: '💰',
      pinnedEligible: true,
    },
  }),
  staffRoute({
    id: 'donation-create',
    title: 'Record Donation',
    section: 'Finance',
    path: '/donations/new',
  }),
  staffRoute({
    id: 'donation-detail',
    title: 'Donation Detail',
    section: 'Finance',
    path: '/donations/:id',
  }),
  staffRoute({
    id: 'donation-edit',
    title: 'Edit Donation',
    section: 'Finance',
    path: '/donations/:id/edit',
  }),
  staffRoute({
    id: 'donation-payment',
    title: 'Donation Payment',
    section: 'Finance',
    path: '/donations/payment',
  }),
  staffRoute({
    id: 'donation-payment-result',
    title: 'Donation Payment Result',
    section: 'Finance',
    path: '/donations/payment-result',
  }),
  staffRoute({
    id: 'recurring-donations',
    title: 'Recurring Donations',
    section: 'Finance',
    path: '/recurring-donations',
    staffNav: {
      group: 'secondary',
      order: 125,
      label: 'Monthly Plans',
      shortLabel: 'Monthly Plans',
      ariaLabel: 'Go to recurring donations',
      icon: '🔁',
      pinnedEligible: true,
    },
  }),
  staffRoute({
    id: 'recurring-donation-detail',
    title: 'Recurring Donation Detail',
    section: 'Finance',
    path: '/recurring-donations/:id',
  }),
  staffRoute({
    id: 'recurring-donation-edit',
    title: 'Edit Recurring Donation',
    section: 'Finance',
    path: '/recurring-donations/:id/edit',
  }),
  staffRoute({
    id: 'reconciliation',
    title: 'Reconciliation',
    section: 'Finance',
    path: '/reconciliation',
    staffNav: {
      group: 'secondary',
      order: 130,
      label: 'Reconciliation',
      shortLabel: 'Reconciliation',
      ariaLabel: 'Go to reconciliation',
      icon: '🧮',
      pinnedEligible: true,
    },
  }),
  staffRoute({
    id: 'analytics',
    title: 'Analytics',
    section: 'Analytics',
    path: '/analytics',
    primaryAction: { label: 'Apply filters', href: '/analytics' },
    staffNav: {
      group: 'utility',
      order: 140,
      label: 'Analytics',
      shortLabel: 'Analytics',
      ariaLabel: 'Go to analytics',
      icon: '📉',
    },
  }),
  staffRoute({
    id: 'dashboard-custom',
    title: 'Custom Dashboard',
    section: 'Analytics',
    path: '/dashboard/custom',
  }),
  staffRoute({
    id: 'reports',
    title: 'Reports',
    section: 'Analytics',
    path: '/reports',
    href: '/reports/builder',
    primaryAction: { label: 'Generate report', href: '/reports/builder' },
    staffNav: {
      group: 'utility',
      order: 150,
      label: 'Reports',
      shortLabel: 'Reports',
      ariaLabel: 'Go to reports',
      icon: '🗂️',
    },
  }),
  staffRoute({
    id: 'reports-builder',
    title: 'Report Builder',
    section: 'Analytics',
    path: '/reports/builder',
    primaryAction: { label: 'Generate report', href: '/reports/builder' },
  }),
  staffRoute({
    id: 'reports-templates',
    title: 'Report Templates',
    section: 'Analytics',
    path: '/reports/templates',
    primaryAction: { label: 'Create custom report', href: '/reports/builder' },
  }),
  staffRoute({
    id: 'reports-saved',
    title: 'Saved Reports',
    section: 'Analytics',
    path: '/reports/saved',
  }),
  staffRoute({
    id: 'reports-scheduled',
    title: 'Scheduled Reports',
    section: 'Analytics',
    path: '/reports/scheduled',
    staffNav: {
      group: 'secondary',
      order: 160,
      label: 'Scheduled Reports',
      shortLabel: 'Schedules',
      ariaLabel: 'Go to scheduled reports',
      icon: '🗓️',
      pinnedEligible: true,
    },
  }),
  staffRoute({
    id: 'reports-outcomes',
    title: 'Outcomes Report',
    section: 'Analytics',
    path: '/reports/outcomes',
  }),
  staffRoute({
    id: 'reports-workflow-coverage',
    title: 'Workflow Coverage Report',
    section: 'Analytics',
    path: '/reports/workflow-coverage',
  }),
  staffRoute({
    id: 'alerts-overview',
    title: 'Alerts',
    section: 'Analytics',
    path: '/alerts',
    primaryAction: { label: 'Create alert', href: '/alerts' },
    staffNav: {
      group: 'utility',
      order: 170,
      label: 'Alerts',
      shortLabel: 'Alerts',
      ariaLabel: 'Go to alerts',
      icon: '🚨',
    },
  }),
  staffRoute({
    id: 'alerts-instances',
    title: 'Triggered Alerts',
    section: 'Analytics',
    path: '/alerts/instances',
  }),
  staffRoute({
    id: 'alerts-history',
    title: 'Alert History',
    section: 'Analytics',
    path: '/alerts/history',
  }),
  staffRoute({
    id: 'intake-create',
    title: 'New Intake',
    section: 'Core',
    path: '/intake/new',
    primaryAction: { label: 'Create contact', href: '/intake/new' },
  }),
  staffRoute({
    id: 'interaction-create',
    title: 'Note an Interaction',
    section: 'Core',
    path: '/interactions/new',
    primaryAction: { label: 'Create new person', href: '/contacts/new' },
  }),
  staffRoute({
    id: 'people-directory',
    title: 'People Directory',
    section: 'Core',
    path: '/people',
  }),
  staffRoute({
    id: 'linking',
    title: 'Linking',
    section: 'Core',
    path: '/linking',
  }),
  staffRoute({
    id: 'operations',
    title: 'Operations',
    section: 'Core',
    path: '/operations',
  }),
  staffRoute({
    id: 'outreach',
    title: 'Outreach',
    section: 'Core',
    path: '/outreach',
  }),
  settingsRoute({
    id: 'user-settings',
    title: 'User Settings',
    path: '/settings/user',
    featureStatus: 'available',
  }),
  adminRoute({
    id: 'admin-settings',
    title: 'Admin Settings',
    path: '/settings/admin/dashboard',
    aliases: [
      { path: '/settings/admin', exactQuery: true },
      { path: '/settings/admin', query: { section: 'dashboard' } },
    ],
    adminNav: [
      { mode: 'settings', order: 10, label: 'Admin Settings' },
      { mode: 'portal', order: 10, label: 'Admin Settings' },
    ],
  }),
  adminRoute({
    id: 'admin-settings-organization',
    title: 'Organization',
    path: '/settings/admin/organization',
    aliases: [
      '/settings/organization',
      { path: '/settings/admin', query: { section: 'organization' } },
    ],
  }),
  adminRoute({
    id: 'admin-settings-branding',
    title: 'Branding',
    path: '/settings/admin/branding',
    aliases: [{ path: '/settings/admin', query: { section: 'branding' } }],
  }),
  adminRoute({
    id: 'admin-settings-users',
    title: 'Users & Security',
    path: '/settings/admin/users',
    aliases: [{ path: '/settings/admin', query: { section: 'users' } }],
  }),
  adminRoute({
    id: 'admin-settings-email',
    title: 'Email Settings',
    path: '/settings/admin/email',
    aliases: [{ path: '/settings/admin', query: { section: 'email' } }],
  }),
  adminRoute({
    id: 'admin-settings-messaging',
    title: 'Messaging Settings',
    path: '/settings/admin/messaging',
    aliases: [{ path: '/settings/admin', query: { section: 'messaging' } }],
  }),
  adminRoute({
    id: 'admin-settings-outcomes',
    title: 'Outcome Definitions',
    path: '/settings/admin/outcomes',
    aliases: [{ path: '/settings/admin', query: { section: 'outcomes' } }],
  }),
  adminRoute({
    id: 'admin-settings-roles',
    title: 'Roles & Permissions',
    path: '/settings/admin/roles',
    aliases: [{ path: '/settings/admin', query: { section: 'roles' } }],
  }),
  adminRoute({
    id: 'admin-settings-audit-logs',
    title: 'Audit Logs',
    path: '/settings/admin/audit_logs',
    aliases: ['/admin/audit-logs', { path: '/settings/admin', query: { section: 'audit_logs' } }],
  }),
  adminRoute({
    id: 'admin-settings-other',
    title: 'Other Settings',
    path: '/settings/admin/other',
    aliases: [{ path: '/settings/admin', query: { section: 'other' } }],
  }),
  settingsRoute({
    id: 'api-settings',
    title: 'API Settings',
    path: '/settings/api',
    adminNav: { mode: 'settings', order: 120, label: 'API Settings' },
    featureStatus: 'available',
  }),
  settingsRoute({
    id: 'navigation-settings',
    title: 'Navigation Settings',
    path: '/settings/navigation',
    adminNav: { mode: 'settings', order: 130, label: 'Navigation' },
    featureStatus: 'available',
  }),
  adminRoute({
    id: 'backup-settings',
    title: 'Data Backup',
    path: '/settings/backup',
    adminNav: { mode: 'settings', order: 140, label: 'Data Backup' },
  }),
  settingsRoute({
    id: 'email-marketing',
    title: 'Email Marketing',
    path: '/settings/email-marketing',
    aliases: ['/email-marketing'],
    adminNav: { mode: 'settings', order: 150, label: 'Email Marketing' },
    featureStatus: 'available',
  }),
  adminRoute({
    id: 'social-media',
    title: 'Social Media',
    path: '/settings/social-media',
    adminNav: { mode: 'settings', order: 160, label: 'Social Media' },
    featureStatus: 'available',
  }),
  adminRoute({
    id: 'portal-admin-access',
    title: 'Portal Access',
    path: '/settings/admin/portal/access',
    aliases: ['/settings/admin/portal'],
    adminNav: [
      {
        mode: 'settings',
        order: 110,
        label: 'Portal Ops',
        matchPrefixes: ['/settings/admin/portal'],
      },
      {
        mode: 'portal',
        order: 20,
        label: 'Access',
      },
    ],
  }),
  adminRoute({
    id: 'portal-admin-users',
    title: 'Portal Users',
    path: '/settings/admin/portal/users',
    adminNav: { mode: 'portal', order: 30, label: 'Users' },
  }),
  adminRoute({
    id: 'portal-admin-conversations',
    title: 'Portal Conversations',
    path: '/settings/admin/portal/conversations',
    adminNav: { mode: 'portal', order: 40, label: 'Conversations' },
  }),
  adminRoute({
    id: 'portal-admin-appointments',
    title: 'Portal Appointments',
    path: '/settings/admin/portal/appointments',
    adminNav: { mode: 'portal', order: 50, label: 'Appointments' },
  }),
  adminRoute({
    id: 'portal-admin-slots',
    title: 'Portal Slots',
    path: '/settings/admin/portal/slots',
    adminNav: { mode: 'portal', order: 60, label: 'Slots' },
  }),
  staffRoute({
    id: 'website-builder',
    title: 'Website Builder',
    section: 'Builder',
    path: '/website-builder',
  }),
  staffRoute({
    id: 'websites',
    title: 'Websites',
    section: 'Websites',
    path: '/websites',
  }),
  staffRoute({
    id: 'website-console-redirect',
    title: 'Website Console',
    section: 'Websites',
    path: '/websites/:siteId',
  }),
  staffRoute({
    id: 'website-console-overview',
    title: 'Website Overview',
    section: 'Websites',
    path: '/websites/:siteId/overview',
  }),
  staffRoute({
    id: 'website-console-content',
    title: 'Website Content',
    section: 'Websites',
    path: '/websites/:siteId/content',
  }),
  staffRoute({
    id: 'website-console-forms',
    title: 'Website Forms',
    section: 'Websites',
    path: '/websites/:siteId/forms',
  }),
  staffRoute({
    id: 'website-console-integrations',
    title: 'Website Integrations',
    section: 'Websites',
    path: '/websites/:siteId/integrations',
  }),
  staffRoute({
    id: 'website-console-publishing',
    title: 'Website Publishing',
    section: 'Websites',
    path: '/websites/:siteId/publishing',
  }),
  staffRoute({
    id: 'website-console-builder',
    title: 'Website Builder (Site)',
    section: 'Websites',
    path: '/websites/:siteId/builder',
  }),
  staffRoute({
    id: 'website-builder-preview',
    title: 'Website Preview',
    section: 'Builder',
    path: '/website-builder/:templateId/preview',
  }),
  staffRoute({
    id: 'website-builder-editor',
    title: 'Website Editor',
    section: 'Builder',
    path: '/website-builder/:templateId',
  }),
];
