import type { RouteCatalogEntry } from './types';
import { staffRoute } from './shared';

export const staffEngagementRouteCatalogEntries: readonly RouteCatalogEntry[] = [
  staffRoute({
    id: 'events',
    title: 'Events',
    section: 'Engagement',
    path: '/events',
    primaryAction: { label: 'Create event', href: '/events/new' },
    mobilePriority: 50,
    staffNav: {
      group: 'primary',
      order: 50,
      label: 'Events',
      shortLabel: 'Events',
      ariaLabel: 'Go to events',
      icon: '📅',
      pinnedEligible: true,
    },
  }),
  staffRoute({
    id: 'events-calendar',
    title: 'Event Calendar',
    section: 'Engagement',
    path: '/events/calendar',
  }),
  staffRoute({
    id: 'events-check-in',
    title: 'Event Check-In',
    section: 'Engagement',
    path: '/events/check-in',
  }),
  staffRoute({
    id: 'event-create',
    title: 'Create Event',
    section: 'Engagement',
    path: '/events/new',
    primaryAction: { label: 'Create event', href: '/events/new' },
  }),
  staffRoute({
    id: 'event-detail',
    title: 'Event Detail',
    section: 'Engagement',
    path: '/events/:id',
  }),
  staffRoute({
    id: 'event-edit',
    title: 'Edit Event',
    section: 'Engagement',
    path: '/events/:id/edit',
  }),
  staffRoute({
    id: 'tasks',
    title: 'Tasks',
    section: 'Engagement',
    path: '/tasks',
    primaryAction: { label: 'New task', href: '/tasks/new' },
    mobilePriority: 30,
    staffNav: {
      group: 'primary',
      order: 60,
      label: 'Tasks',
      shortLabel: 'Tasks',
      ariaLabel: 'Go to tasks',
      icon: '✓',
      pinnedEligible: true,
    },
  }),
  staffRoute({
    id: 'task-create',
    title: 'Create Task',
    section: 'Engagement',
    path: '/tasks/new',
    primaryAction: { label: 'Save task', href: '/tasks/new' },
  }),
  staffRoute({
    id: 'task-detail',
    title: 'Task Detail',
    section: 'Engagement',
    path: '/tasks/:id',
  }),
  staffRoute({
    id: 'task-edit',
    title: 'Edit Task',
    section: 'Engagement',
    path: '/tasks/:id/edit',
  }),
  staffRoute({
    id: 'cases',
    title: 'Cases',
    section: 'Engagement',
    path: '/cases',
    primaryAction: { label: 'New case', href: '/cases/new' },
    mobilePriority: 40,
    staffNav: {
      group: 'primary',
      order: 70,
      label: 'Cases',
      shortLabel: 'Cases',
      ariaLabel: 'Go to cases',
      icon: '📋',
      pinnedEligible: true,
    },
  }),
  staffRoute({
    id: 'case-create',
    title: 'Create Case',
    section: 'Engagement',
    path: '/cases/new',
    primaryAction: { label: 'Save case', href: '/cases/new' },
  }),
  staffRoute({
    id: 'case-detail',
    title: 'Case Detail',
    section: 'Engagement',
    path: '/cases/:id',
  }),
  staffRoute({
    id: 'case-edit',
    title: 'Edit Case',
    section: 'Engagement',
    path: '/cases/:id/edit',
  }),
  staffRoute({
    id: 'follow-ups',
    title: 'Follow-Ups',
    section: 'Engagement',
    path: '/follow-ups',
    primaryAction: { label: 'Create follow-up', href: '/follow-ups' },
    staffNav: {
      group: 'secondary',
      order: 80,
      label: 'Follow-Ups',
      shortLabel: 'Follow-ups',
      ariaLabel: 'Go to follow-ups',
      icon: '🔔',
      pinnedEligible: true,
    },
  }),
  staffRoute({
    id: 'opportunities',
    title: 'Opportunities',
    section: 'Engagement',
    path: '/opportunities',
    primaryAction: { label: 'New opportunity', href: '/opportunities' },
    staffNav: {
      group: 'secondary',
      order: 90,
      label: 'Opportunities',
      shortLabel: 'Pipeline',
      ariaLabel: 'Go to opportunities',
      icon: '📈',
      pinnedEligible: true,
    },
  }),
  staffRoute({
    id: 'external-service-providers',
    title: 'External Service Providers',
    section: 'Engagement',
    path: '/external-service-providers',
    staffNav: {
      group: 'secondary',
      order: 100,
      label: 'Providers',
      shortLabel: 'Providers',
      ariaLabel: 'Go to external service providers',
      icon: '🩺',
      pinnedEligible: true,
    },
  }),
  staffRoute({
    id: 'team-chat',
    title: 'Team Messenger',
    section: 'Engagement',
    path: '/team-chat',
    featureFlagEnv: 'VITE_TEAM_CHAT_ENABLED',
    showInMobileDrawerUtilities: true,
    staffNav: {
      group: 'secondary',
      order: 110,
      label: 'Team Messenger',
      shortLabel: 'Messenger',
      ariaLabel: 'Go to team messenger',
      icon: '💬',
      pinnedEligible: true,
    },
  }),
  staffRoute({
    id: 'meetings',
    title: 'Meetings',
    section: 'Engagement',
    path: '/meetings',
    primaryAction: { label: 'New meeting', href: '/meetings/new' },
    staffNav: {
      group: 'secondary',
      order: 120,
      label: 'Meetings',
      shortLabel: 'Meetings',
      ariaLabel: 'Go to meetings',
      icon: '🤝',
      pinnedEligible: true,
    },
  }),
  staffRoute({
    id: 'meeting-create',
    title: 'Create Meeting',
    section: 'Engagement',
    path: '/meetings/new',
  }),
  staffRoute({
    id: 'meeting-detail',
    title: 'Meeting Detail',
    section: 'Engagement',
    path: '/meetings/:id',
  }),
  staffRoute({
    id: 'meeting-edit',
    title: 'Edit Meeting',
    section: 'Engagement',
    path: '/meetings/:id/edit',
  }),
];
