import type { RouteCatalogEntry } from './types';
import {
  staffAdminRouteCatalogEntries,
} from './staffAdminRoutes';
import { staffEngagementRouteCatalogEntries } from './staffEngagementRoutes';
import { staffFinanceRouteCatalogEntries } from './staffFinanceRoutes';
import { staffHomeRouteCatalogEntries } from './staffHomeRoutes';
import { staffInsightsRouteCatalogEntries } from './staffInsightsRoutes';
import { staffPeopleRouteCatalogEntries } from './staffPeopleRoutes';
import { staffPublishingRouteCatalogEntries } from './staffPublishingRoutes';

// Keep literal path/href targets in this file so the regex-based route audit can
// validate canonical coverage even though the runtime catalog is split by section.
export const staffRouteCatalogAuditTargets = [
  { path: '/dashboard' },
  { href: '/intake/new' },
  { path: '/contacts' },
  { href: '/contacts/new' },
  { path: '/contacts/new' },
  { path: '/contacts/:id' },
  { path: '/contacts/:id/edit' },
  { path: '/contacts/:id/print' },
  { path: '/accounts' },
  { href: '/accounts/new' },
  { path: '/accounts/new' },
  { path: '/accounts/:id' },
  { path: '/accounts/:id/edit' },
  { path: '/volunteers' },
  { href: '/volunteers/new' },
  { path: '/volunteers/new' },
  { path: '/volunteers/:id' },
  { path: '/volunteers/:id/edit' },
  { path: '/volunteers/:volunteerId/assignments/new' },
  { path: '/volunteers/:volunteerId/assignments/:assignmentId/edit' },
  { path: '/events' },
  { href: '/events/new' },
  { path: '/events/calendar' },
  { path: '/events/check-in' },
  { path: '/events/new' },
  { path: '/events/:id' },
  { path: '/events/:id/edit' },
  { path: '/tasks' },
  { href: '/tasks/new' },
  { path: '/tasks/new' },
  { path: '/tasks/:id' },
  { path: '/tasks/:id/edit' },
  { path: '/cases' },
  { href: '/cases/new' },
  { path: '/cases/new' },
  { path: '/cases/:id' },
  { path: '/cases/:id/edit' },
  { path: '/follow-ups' },
  { href: '/follow-ups' },
  { path: '/opportunities' },
  { href: '/opportunities' },
  { path: '/external-service-providers' },
  { path: '/team-chat' },
  { path: '/donations' },
  { href: '/donations/new' },
  { path: '/donations/new' },
  { path: '/donations/:id' },
  { path: '/donations/:id/edit' },
  { path: '/donations/payment' },
  { path: '/donations/payment-result' },
  { path: '/recurring-donations' },
  { path: '/recurring-donations/:id' },
  { path: '/recurring-donations/:id/edit' },
  { path: '/reconciliation' },
  { path: '/grants' },
  { href: '/grants/applications' },
  { path: '/grants/funders' },
  { path: '/grants/programs' },
  { path: '/grants/recipients' },
  { path: '/grants/funded-programs' },
  { path: '/grants/applications' },
  { path: '/grants/awards' },
  { path: '/grants/disbursements' },
  { path: '/grants/reports' },
  { path: '/grants/documents' },
  { path: '/grants/calendar' },
  { path: '/grants/activities' },
  { path: '/analytics' },
  { href: '/analytics' },
  { path: '/dashboard/custom' },
  { path: '/reports' },
  { href: '/reports/builder' },
  { path: '/reports/builder' },
  { path: '/reports/templates' },
  { path: '/reports/saved' },
  { path: '/reports/scheduled' },
  { path: '/reports/outcomes' },
  { path: '/reports/workflow-coverage' },
  { path: '/alerts' },
  { href: '/alerts' },
  { path: '/alerts/instances' },
  { path: '/alerts/history' },
  { path: '/intake/new' },
  { path: '/interactions/new' },
  { path: '/people' },
  { path: '/linking' },
  { path: '/operations' },
  { path: '/outreach' },
  { path: '/settings/user' },
  { path: '/settings/email-marketing' },
  { path: '/website-builder' },
  { path: '/websites' },
  { href: '/website-builder' },
  { path: '/websites/:siteId' },
  { path: '/websites/:siteId/overview' },
  { path: '/websites/:siteId/content' },
  { path: '/websites/:siteId/newsletters' },
  { path: '/websites/:siteId/forms' },
  { path: '/websites/:siteId/integrations' },
  { path: '/websites/:siteId/publishing' },
  { path: '/websites/:siteId/builder' },
  { path: '/website-builder/:templateId/preview' },
  { path: '/website-builder/:templateId' },
  { path: '/settings/admin/approvals' },
  { path: '/settings/admin/dashboard' },
  { path: '/settings/admin/organization' },
  { path: '/settings/admin/workspace_modules' },
  { path: '/settings/admin/branding' },
  { path: '/settings/admin/users' },
  { path: '/settings/admin/groups' },
  { path: '/settings/admin/communications' },
  { path: '/settings/admin/messaging' },
  { path: '/settings/admin/outcomes' },
  { path: '/settings/admin/roles' },
  { path: '/settings/admin/audit_logs' },
  { path: '/settings/admin/other' },
  { path: '/settings/api' },
  { path: '/settings/navigation' },
  { path: '/settings/backup' },
  { path: '/settings/communications' },
  { path: '/settings/social-media' },
  { path: '/settings/admin/portal/access' },
  { path: '/settings/admin/portal/users' },
  { path: '/settings/admin/portal/conversations' },
  { path: '/settings/admin/portal/appointments' },
  { path: '/settings/admin/portal/slots' },
] as const;

export const staffRouteCatalogEntries: readonly RouteCatalogEntry[] = [
  ...staffHomeRouteCatalogEntries,
  ...staffPeopleRouteCatalogEntries,
  ...staffEngagementRouteCatalogEntries,
  ...staffFinanceRouteCatalogEntries,
  ...staffInsightsRouteCatalogEntries,
  ...staffAdminRouteCatalogEntries,
  ...staffPublishingRouteCatalogEntries,
];
