export {
  register,
  checkSetupStatus,
  setupFirstUser,
  forgotPassword,
  validateResetToken,
  resetPassword,
  getRegistrationStatus,
  login,
  logout,
  getCurrentUser,
  checkAccess,
  getPreferences,
  updatePreferences,
  updatePreferenceKey,
  getProfile,
  updateProfile,
  changePassword,
} from '@modules/auth/controllers/authController';
