import { Router } from 'express';
import { portalV2Routes } from '@modules/portal';
import { eventsV2Routes } from '@modules/events';
import { casesV2Routes } from '@modules/cases';
import { contactsV2Routes } from '@modules/contacts';
import { opportunitiesV2Routes } from '@modules/opportunities';
import { teamChatV2Routes } from '@modules/teamChat';
import { accountsV2Routes } from '@modules/accounts';
import { volunteersV2Routes } from '@modules/volunteers';
import { tasksV2Routes } from '@modules/tasks';
import { analyticsV2Routes } from '@modules/analytics';
import { reportsV2Routes } from '@modules/reports';
import { savedReportsV2Routes } from '@modules/savedReports';
import { scheduledReportsV2Routes } from '@modules/scheduledReports';
import { dashboardV2Routes } from '@modules/dashboard';
import { followUpsV2Routes } from '@modules/followUps';
import activityRoutes from '@routes/activities';
import adminRoutes from '@routes/admin';
import alertRoutes from '@routes/alerts';
import authRoutes from '@routes/auth';
import backupRoutes from '@routes/backup';
import donationRoutes from '@routes/donations';
import exportRoutes from '@routes/export';
import externalServiceProviderRoutes from '@routes/externalServiceProviders';
import ingestRoutes from '@routes/ingest';
import invitationRoutes from '@routes/invitations';
import mailchimpRoutes from '@routes/mailchimp';
import meetingRoutes from '@routes/meetings';
import paymentRoutes from '@routes/payments';
import plausibleRoutes from '@routes/plausibleProxy';
import publicReportRoutes from '@routes/publicReports';
import reconciliationRoutes from '@routes/reconciliation';
import publishingRoutes from '@routes/publishing';
import templateRoutes from '@routes/templates';
import userRoutes from '@routes/users';
import webhookRoutes from '@routes/webhooks';
import portalAuthRoutes from '@routes/portalAuth';
import portalAdminRoutes from '@routes/portalAdmin';

export const apiV2Routes = Router();

apiV2Routes.use('/auth', authRoutes);
apiV2Routes.use('/users', userRoutes);
apiV2Routes.use('/ingest', ingestRoutes);
apiV2Routes.use('/admin', adminRoutes);
apiV2Routes.use('/backup', backupRoutes);
apiV2Routes.use('/plausible', plausibleRoutes);
apiV2Routes.use('/activities', activityRoutes);
apiV2Routes.use('/alerts', alertRoutes);
apiV2Routes.use('/donations', donationRoutes);
apiV2Routes.use('/export', exportRoutes);
apiV2Routes.use('/external-service-providers', externalServiceProviderRoutes);
apiV2Routes.use('/invitations', invitationRoutes);
apiV2Routes.use('/mailchimp', mailchimpRoutes);
apiV2Routes.use('/meetings', meetingRoutes);
apiV2Routes.use('/payments', paymentRoutes);
apiV2Routes.use('/public/reports', publicReportRoutes);
apiV2Routes.use('/reconciliation', reconciliationRoutes);
apiV2Routes.use('/sites', publishingRoutes);
apiV2Routes.use('/templates', templateRoutes);
apiV2Routes.use('/webhooks', webhookRoutes);
apiV2Routes.use('/portal/auth', portalAuthRoutes);
apiV2Routes.use('/portal/admin', portalAdminRoutes);
apiV2Routes.use('/portal', portalV2Routes);
apiV2Routes.use('/events', eventsV2Routes);
apiV2Routes.use('/accounts', accountsV2Routes);
apiV2Routes.use('/volunteers', volunteersV2Routes);
apiV2Routes.use('/tasks', tasksV2Routes);
apiV2Routes.use('/analytics', analyticsV2Routes);
apiV2Routes.use('/reports', reportsV2Routes);
apiV2Routes.use('/saved-reports', savedReportsV2Routes);
apiV2Routes.use('/scheduled-reports', scheduledReportsV2Routes);
apiV2Routes.use('/dashboard', dashboardV2Routes);
apiV2Routes.use('/follow-ups', followUpsV2Routes);
apiV2Routes.use('/cases', casesV2Routes);
apiV2Routes.use('/contacts', contactsV2Routes);
apiV2Routes.use('/opportunities', opportunitiesV2Routes);
apiV2Routes.use('/team-chat', teamChatV2Routes);
