"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.schemaRegistry = void 0;
// Keep this registry aligned with TypeScript API types and migrations.
// It focuses on import-relevant fields (things you'd expect in CSV/Excel exports).
exports.schemaRegistry = [
    {
        table: 'accounts',
        label: 'Accounts',
        aliases: ['account', 'organization', 'org', 'company', 'constituent', 'donor'],
        fields: [
            { field: 'account_id', type: 'uuid', aliases: ['id', 'accountid'] },
            { field: 'account_number', type: 'string', aliases: ['acct_no', 'acct', 'account_no', 'accountnumber'] },
            { field: 'account_name', type: 'string', required: true, aliases: ['name', 'organization', 'org_name'] },
            { field: 'account_type', type: 'enum', aliases: ['type', 'kind'] },
            { field: 'category', type: 'enum', aliases: ['segment', 'class', 'group'] },
            { field: 'email', type: 'string', aliases: ['email_address', 'e-mail'] },
            { field: 'phone', type: 'string', aliases: ['telephone', 'tel', 'main_phone'] },
            { field: 'website', type: 'string', aliases: ['url', 'web'] },
            { field: 'description', type: 'string', aliases: ['notes', 'memo'] },
            { field: 'address_line1', type: 'string', aliases: ['address1', 'street', 'street1', 'line1'] },
            { field: 'address_line2', type: 'string', aliases: ['address2', 'street2', 'line2', 'suite', 'apt'] },
            { field: 'city', type: 'string' },
            { field: 'state_province', type: 'string', aliases: ['state', 'province', 'region'] },
            { field: 'postal_code', type: 'string', aliases: ['zip', 'zipcode', 'postal', 'post_code'] },
            { field: 'country', type: 'string' },
            { field: 'tax_id', type: 'string', aliases: ['ein', 'tin', 'ssn'] },
        ],
    },
    {
        table: 'contacts',
        label: 'Contacts',
        aliases: ['contact', 'people', 'person', 'constituents', 'supporters'],
        fields: [
            { field: 'contact_id', type: 'uuid', aliases: ['id', 'contactid'] },
            { field: 'account_id', type: 'uuid', aliases: ['account', 'accountid', 'organization_id'] },
            { field: 'first_name', type: 'string', required: true, aliases: ['firstname', 'given_name', 'forename'] },
            { field: 'last_name', type: 'string', required: true, aliases: ['lastname', 'surname', 'family_name'] },
            { field: 'middle_name', type: 'string', aliases: ['middlename', 'mi'] },
            { field: 'salutation', type: 'string', aliases: ['title', 'prefix'] },
            { field: 'suffix', type: 'string', aliases: ['post_nominal'] },
            { field: 'birth_date', type: 'date', aliases: ['dob', 'birthdate', 'date_of_birth'] },
            { field: 'gender', type: 'string' },
            { field: 'pronouns', type: 'string', aliases: ['pronoun'] },
            { field: 'email', type: 'string', aliases: ['email_address', 'e-mail'] },
            { field: 'phone', type: 'string', aliases: ['telephone', 'tel', 'home_phone', 'work_phone'] },
            { field: 'mobile_phone', type: 'string', aliases: ['mobile', 'cell', 'cell_phone', 'cellphone'] },
            { field: 'job_title', type: 'string', aliases: ['title'] },
            { field: 'department', type: 'string' },
            { field: 'preferred_contact_method', type: 'string', aliases: ['preferred_method', 'contact_method'] },
            { field: 'do_not_email', type: 'boolean', aliases: ['opt_out_email', 'no_email', 'donotemail'] },
            { field: 'do_not_phone', type: 'boolean', aliases: ['opt_out_phone', 'no_phone', 'donotcall'] },
            { field: 'address_line1', type: 'string', aliases: ['address1', 'street', 'street1', 'line1'] },
            { field: 'address_line2', type: 'string', aliases: ['address2', 'street2', 'line2', 'suite', 'apt'] },
            { field: 'city', type: 'string' },
            { field: 'state_province', type: 'string', aliases: ['state', 'province', 'region'] },
            { field: 'postal_code', type: 'string', aliases: ['zip', 'zipcode', 'postal', 'post_code'] },
            { field: 'country', type: 'string' },
            { field: 'notes', type: 'string', aliases: ['note', 'memo', 'comment', 'comments'] },
        ],
    },
    {
        table: 'donations',
        label: 'Donations',
        aliases: ['donation', 'donations', 'contribution', 'gift', 'giving', 'payments'],
        fields: [
            { field: 'donation_id', type: 'uuid', aliases: ['id', 'donationid'] },
            { field: 'donation_number', type: 'string', aliases: ['receipt_number', 'gift_id', 'donation_no'] },
            { field: 'account_id', type: 'uuid', aliases: ['account', 'accountid', 'org_id'] },
            { field: 'contact_id', type: 'uuid', aliases: ['contact', 'contactid', 'person_id', 'donor_id'] },
            { field: 'amount', type: 'number', required: true, aliases: ['gift_amount', 'donation_amount', 'total', 'value'] },
            { field: 'currency', type: 'string', aliases: ['curr'] },
            { field: 'donation_date', type: 'datetime', required: true, aliases: ['date', 'gift_date', 'received_date'] },
            { field: 'payment_method', type: 'enum', aliases: ['method', 'tender'] },
            { field: 'payment_status', type: 'enum', aliases: ['status'] },
            { field: 'transaction_id', type: 'string', aliases: ['txn_id', 'stripe_charge_id'] },
            { field: 'campaign_name', type: 'string', aliases: ['campaign', 'appeal'] },
            { field: 'designation', type: 'string', aliases: ['fund', 'allocation', 'purpose'] },
            { field: 'is_recurring', type: 'boolean', aliases: ['recurring', 'is_monthly'] },
            { field: 'recurring_frequency', type: 'enum', aliases: ['frequency', 'interval'] },
            { field: 'notes', type: 'string', aliases: ['note', 'memo', 'comment', 'comments'] },
            { field: 'receipt_sent', type: 'boolean', aliases: ['sent_receipt'] },
            { field: 'receipt_sent_date', type: 'datetime', aliases: ['receipt_date'] },
        ],
    },
    {
        table: 'events',
        label: 'Events',
        aliases: ['event', 'campaign', 'program', 'meeting'],
        fields: [
            { field: 'event_id', type: 'uuid', aliases: ['id', 'eventid'] },
            { field: 'event_name', type: 'string', required: true, aliases: ['name', 'title'] },
            { field: 'description', type: 'string', aliases: ['details', 'notes'] },
            { field: 'event_type', type: 'string', aliases: ['type', 'category'] },
            { field: 'status', type: 'enum', aliases: ['state'] },
            { field: 'start_date', type: 'datetime', required: true, aliases: ['start', 'start_time', 'starts_at'] },
            { field: 'end_date', type: 'datetime', required: true, aliases: ['end', 'end_time', 'ends_at'] },
            { field: 'location_name', type: 'string', aliases: ['location', 'venue'] },
            { field: 'address_line1', type: 'string', aliases: ['address1', 'street', 'street1', 'line1'] },
            { field: 'address_line2', type: 'string', aliases: ['address2', 'street2', 'line2', 'suite', 'apt'] },
            { field: 'city', type: 'string' },
            { field: 'state_province', type: 'string', aliases: ['state', 'province', 'region'] },
            { field: 'postal_code', type: 'string', aliases: ['zip', 'zipcode', 'postal', 'post_code'] },
            { field: 'country', type: 'string' },
            { field: 'capacity', type: 'number', aliases: ['max', 'max_capacity', 'limit'] },
        ],
    },
    {
        table: 'volunteers',
        label: 'Volunteers',
        aliases: ['volunteer', 'volunteers', 'service'],
        fields: [
            { field: 'volunteer_id', type: 'uuid', aliases: ['id', 'volunteerid'] },
            { field: 'contact_id', type: 'uuid', aliases: ['contact', 'contactid', 'person_id'] },
            { field: 'skills', type: 'string', aliases: ['skill', 'abilities', 'interests'] },
            { field: 'availability_status', type: 'enum', aliases: ['availability', 'status', 'state'] },
            { field: 'availability_notes', type: 'string', aliases: ['availability_note', 'availability_details', 'notes'] },
            { field: 'background_check_status', type: 'enum', aliases: ['bg_check_status', 'background_status'] },
            { field: 'background_check_date', type: 'date', aliases: ['bg_check_date', 'background_date'] },
            { field: 'background_check_expiry', type: 'date', aliases: ['bg_check_expiry', 'background_expiry'] },
            { field: 'preferred_roles', type: 'string', aliases: ['roles', 'volunteer_roles'] },
            { field: 'max_hours_per_week', type: 'number', aliases: ['max_hours', 'hours_per_week'] },
            { field: 'emergency_contact_name', type: 'string', aliases: ['emergency_name', 'ice_name'] },
            { field: 'emergency_contact_phone', type: 'string', aliases: ['emergency_phone', 'ice_phone'] },
            {
                field: 'emergency_contact_relationship',
                type: 'string',
                aliases: ['emergency_relationship', 'ice_relationship'],
            },
        ],
    },
];
//# sourceMappingURL=schemaRegistry.js.map