import type { SchemaTable } from './types';

// Keep this registry aligned with TypeScript API types and migrations.
// It focuses on import-relevant fields (things you'd expect in CSV/Excel exports).
export const schemaRegistry: SchemaTable[] = [
  {
    table: 'accounts',
    label: 'Accounts',
    aliases: ['account', 'organization', 'org', 'company', 'constituent', 'donor'],
    fields: [
      { field: 'account_id', type: 'uuid', aliases: ['id', 'accountid'] },
      { field: 'account_number', type: 'string', aliases: ['acct_no', 'acct', 'account_no', 'accountnumber'] },
      { field: 'account_name', type: 'string', required: true, aliases: ['name', 'organization', 'org_name'] },
      { field: 'account_type', type: 'enum', aliases: ['type', 'kind'] },
      { field: 'category', type: 'enum', aliases: ['segment', 'class', 'group'] },
      { field: 'email', type: 'string', aliases: ['email_address', 'e-mail'] },
      { field: 'phone', type: 'string', aliases: ['telephone', 'tel', 'main_phone'] },
      { field: 'website', type: 'string', aliases: ['url', 'web'] },
      { field: 'description', type: 'string', aliases: ['notes', 'memo'] },
      { field: 'address_line1', type: 'string', aliases: ['address1', 'street', 'street1', 'line1'] },
      { field: 'address_line2', type: 'string', aliases: ['address2', 'street2', 'line2', 'suite', 'apt'] },
      { field: 'city', type: 'string' },
      { field: 'state_province', type: 'string', aliases: ['state', 'province', 'region'] },
      { field: 'postal_code', type: 'string', aliases: ['zip', 'zipcode', 'postal', 'post_code'] },
      { field: 'country', type: 'string' },
      { field: 'tax_id', type: 'string', aliases: ['ein', 'tin', 'ssn'] },
      { field: 'is_active', type: 'boolean', aliases: ['active', 'enabled'] },
    ],
  },
  {
    table: 'contacts',
    label: 'Contacts',
    aliases: ['contact', 'people', 'person', 'constituents', 'supporters'],
    fields: [
      { field: 'contact_id', type: 'uuid', aliases: ['id', 'contactid'] },
      { field: 'account_id', type: 'uuid', aliases: ['account', 'accountid', 'organization_id'] },
      { field: 'account_number', type: 'string', aliases: ['account_no', 'acct_no', 'accountnumber'] },
      { field: 'first_name', type: 'string', required: true, aliases: ['firstname', 'given_name', 'forename'] },
      { field: 'last_name', type: 'string', required: true, aliases: ['lastname', 'surname', 'family_name'] },
      { field: 'middle_name', type: 'string', aliases: ['middlename', 'mi'] },
      { field: 'salutation', type: 'string', aliases: ['title', 'prefix'] },
      { field: 'suffix', type: 'string', aliases: ['post_nominal'] },
      { field: 'birth_date', type: 'date', aliases: ['dob', 'birthdate', 'date_of_birth'] },
      { field: 'gender', type: 'string' },
      { field: 'pronouns', type: 'string', aliases: ['pronoun'] },
      {
        field: 'phn',
        type: 'string',
        aliases: ['personal_health_number', 'personal_health_no', 'health_number', 'health_no', 'phn_number'],
      },
      { field: 'email', type: 'string', aliases: ['email_address', 'e-mail'] },
      { field: 'phone', type: 'string', aliases: ['telephone', 'tel', 'home_phone', 'work_phone'] },
      { field: 'mobile_phone', type: 'string', aliases: ['mobile', 'cell', 'cell_phone', 'cellphone'] },
      { field: 'job_title', type: 'string', aliases: ['title'] },
      { field: 'department', type: 'string' },
      { field: 'preferred_contact_method', type: 'string', aliases: ['preferred_method', 'contact_method'] },
      { field: 'do_not_email', type: 'boolean', aliases: ['opt_out_email', 'no_email', 'donotemail'] },
      { field: 'do_not_phone', type: 'boolean', aliases: ['opt_out_phone', 'no_phone', 'donotcall'] },
      { field: 'address_line1', type: 'string', aliases: ['address1', 'street', 'street1', 'line1'] },
      { field: 'address_line2', type: 'string', aliases: ['address2', 'street2', 'line2', 'suite', 'apt'] },
      { field: 'city', type: 'string' },
      { field: 'state_province', type: 'string', aliases: ['state', 'province', 'region'] },
      { field: 'postal_code', type: 'string', aliases: ['zip', 'zipcode', 'postal', 'post_code'] },
      { field: 'country', type: 'string' },
      { field: 'notes', type: 'string', aliases: ['note', 'memo', 'comment', 'comments'] },
      { field: 'tags', type: 'string', aliases: ['labels', 'segments'] },
      { field: 'roles', type: 'string', aliases: ['role', 'contact_roles'] },
      { field: 'is_active', type: 'boolean', aliases: ['active', 'enabled'] },
    ],
  },
  {
    table: 'donations',
    label: 'Donations',
    aliases: ['donation', 'donations', 'contribution', 'gift', 'giving', 'payments'],
    fields: [
      { field: 'donation_id', type: 'uuid', aliases: ['id', 'donationid'] },
      { field: 'donation_number', type: 'string', aliases: ['receipt_number', 'gift_id', 'donation_no'] },
      { field: 'account_id', type: 'uuid', aliases: ['account', 'accountid', 'org_id'] },
      { field: 'contact_id', type: 'uuid', aliases: ['contact', 'contactid', 'person_id', 'donor_id'] },
      { field: 'amount', type: 'number', required: true, aliases: ['gift_amount', 'donation_amount', 'total', 'value'] },
      { field: 'currency', type: 'string', aliases: ['curr'] },
      { field: 'donation_date', type: 'datetime', required: true, aliases: ['date', 'gift_date', 'received_date'] },
      { field: 'payment_method', type: 'enum', aliases: ['method', 'tender'] },
      { field: 'payment_status', type: 'enum', aliases: ['status'] },
      { field: 'transaction_id', type: 'string', aliases: ['txn_id', 'stripe_charge_id'] },
      { field: 'campaign_name', type: 'string', aliases: ['campaign', 'appeal'] },
      { field: 'designation', type: 'string', aliases: ['fund', 'allocation', 'purpose'] },
      { field: 'is_recurring', type: 'boolean', aliases: ['recurring', 'is_monthly'] },
      { field: 'recurring_frequency', type: 'enum', aliases: ['frequency', 'interval'] },
      { field: 'notes', type: 'string', aliases: ['note', 'memo', 'comment', 'comments'] },
      { field: 'receipt_sent', type: 'boolean', aliases: ['sent_receipt'] },
      { field: 'receipt_sent_date', type: 'datetime', aliases: ['receipt_date'] },
    ],
  },
  {
    table: 'events',
    label: 'Events',
    aliases: ['event', 'campaign', 'program', 'meeting'],
    fields: [
      { field: 'event_id', type: 'uuid', aliases: ['id', 'eventid'] },
      { field: 'event_name', type: 'string', required: true, aliases: ['name', 'title'] },
      { field: 'description', type: 'string', aliases: ['details', 'notes'] },
      { field: 'event_type', type: 'string', aliases: ['type', 'category'] },
      { field: 'status', type: 'enum', aliases: ['state'] },
      { field: 'start_date', type: 'datetime', required: true, aliases: ['start', 'start_time', 'starts_at'] },
      { field: 'end_date', type: 'datetime', required: true, aliases: ['end', 'end_time', 'ends_at'] },
      { field: 'location_name', type: 'string', aliases: ['location', 'venue'] },
      { field: 'address_line1', type: 'string', aliases: ['address1', 'street', 'street1', 'line1'] },
      { field: 'address_line2', type: 'string', aliases: ['address2', 'street2', 'line2', 'suite', 'apt'] },
      { field: 'city', type: 'string' },
      { field: 'state_province', type: 'string', aliases: ['state', 'province', 'region'] },
      { field: 'postal_code', type: 'string', aliases: ['zip', 'zipcode', 'postal', 'post_code'] },
      { field: 'country', type: 'string' },
      { field: 'capacity', type: 'number', aliases: ['max', 'max_capacity', 'limit'] },
    ],
  },
  {
    table: 'event_registrations',
    label: 'Event Registrations',
    aliases: ['event_registration', 'registration', 'attendance', 'checkin', 'check_in'],
    fields: [
      { field: 'registration_id', type: 'uuid', aliases: ['id', 'eventregistrationid'] },
      { field: 'event_id', type: 'uuid', required: true, aliases: ['event', 'eventid'] },
      { field: 'contact_id', type: 'uuid', required: true, aliases: ['contact', 'contactid', 'participant_id'] },
      { field: 'registration_status', type: 'enum', aliases: ['status', 'attendance_status'] },
      { field: 'checked_in', type: 'boolean', aliases: ['attended', 'present', 'checkedin'] },
      { field: 'check_in_time', type: 'datetime', aliases: ['attendance_time', 'checkin_time'] },
      { field: 'notes', type: 'string', aliases: ['note', 'memo', 'comment', 'comments'] },
    ],
  },
  {
    table: 'volunteers',
    label: 'Volunteers',
    aliases: ['volunteer', 'volunteers', 'service'],
    fields: [
      { field: 'volunteer_id', type: 'uuid', aliases: ['id', 'volunteerid'] },
      { field: 'contact_id', type: 'uuid', aliases: ['contact', 'contactid', 'person_id'] },
      { field: 'account_id', type: 'uuid', aliases: ['account', 'accountid', 'organization_id'] },
      { field: 'account_number', type: 'string', aliases: ['account_no', 'acct_no', 'accountnumber'] },
      { field: 'first_name', type: 'string', aliases: ['firstname', 'given_name', 'forename'] },
      { field: 'last_name', type: 'string', aliases: ['lastname', 'surname', 'family_name'] },
      { field: 'email', type: 'string', aliases: ['email_address', 'e-mail'] },
      { field: 'phone', type: 'string', aliases: ['telephone', 'tel', 'home_phone', 'work_phone'] },
      { field: 'mobile_phone', type: 'string', aliases: ['mobile', 'cell', 'cell_phone', 'cellphone'] },
      { field: 'tags', type: 'string', aliases: ['labels', 'segments'] },
      { field: 'roles', type: 'string', aliases: ['role', 'contact_roles'] },
      { field: 'skills', type: 'string', aliases: ['skill', 'abilities', 'interests'] },
      { field: 'availability_status', type: 'enum', aliases: ['availability', 'status', 'state'] },
      { field: 'availability_notes', type: 'string', aliases: ['availability_note', 'availability_details', 'notes'] },
      { field: 'background_check_status', type: 'enum', aliases: ['bg_check_status', 'background_status'] },
      { field: 'background_check_date', type: 'date', aliases: ['bg_check_date', 'background_date'] },
      { field: 'background_check_expiry', type: 'date', aliases: ['bg_check_expiry', 'background_expiry'] },
      { field: 'preferred_roles', type: 'string', aliases: ['roles', 'volunteer_roles'] },
      { field: 'certifications', type: 'string', aliases: ['certs', 'credentials'] },
      { field: 'max_hours_per_week', type: 'number', aliases: ['max_hours', 'hours_per_week'] },
      { field: 'emergency_contact_name', type: 'string', aliases: ['emergency_name', 'ice_name'] },
      { field: 'emergency_contact_phone', type: 'string', aliases: ['emergency_phone', 'ice_phone'] },
      {
        field: 'emergency_contact_relationship',
        type: 'string',
        aliases: ['emergency_relationship', 'ice_relationship'],
      },
      { field: 'is_active', type: 'boolean', aliases: ['active', 'enabled'] },
    ],
  },
  {
    table: 'activities',
    label: 'Activities',
    aliases: ['activity', 'interaction', 'note', 'engagement', 'timeline'],
    fields: [
      { field: 'activity_id', type: 'uuid', aliases: ['id', 'activityid'] },
      { field: 'contact_id', type: 'uuid', aliases: ['contact', 'contactid', 'person_id'] },
      { field: 'account_id', type: 'uuid', aliases: ['account', 'accountid', 'organization_id'] },
      { field: 'case_id', type: 'uuid', aliases: ['case', 'caseid'] },
      { field: 'event_id', type: 'uuid', aliases: ['event', 'eventid'] },
      { field: 'activity_type', type: 'enum', required: true, aliases: ['type', 'interaction_type'] },
      { field: 'subject', type: 'string', aliases: ['title', 'summary'] },
      { field: 'description', type: 'string', aliases: ['details', 'notes', 'content'] },
      { field: 'activity_date', type: 'datetime', required: true, aliases: ['date', 'datetime', 'occurred_at'] },
      { field: 'status', type: 'enum', aliases: ['state'] },
      { field: 'staff_name', type: 'string', aliases: ['staff', 'worker', 'author'] },
      { field: 'source_table', type: 'string', aliases: ['dataset', 'import_source_table'] },
    ],
  },
  {
    table: 'cases',
    label: 'Cases',
    aliases: ['case', 'casework', 'client_case', 'service_case'],
    fields: [
      { field: 'case_id', type: 'uuid', aliases: ['id', 'caseid'] },
      { field: 'contact_id', type: 'uuid', required: true, aliases: ['contact', 'contactid', 'client_id'] },
      { field: 'account_id', type: 'uuid', aliases: ['account', 'accountid', 'organization_id'] },
      { field: 'case_number', type: 'string', aliases: ['number', 'reference_number'] },
      { field: 'case_type', type: 'string', aliases: ['type', 'case_type_name'] },
      { field: 'status', type: 'enum', required: true, aliases: ['state', 'case_status'] },
      { field: 'priority', type: 'enum', aliases: ['urgency'] },
      { field: 'title', type: 'string', required: true, aliases: ['name', 'subject'] },
      { field: 'description', type: 'string', aliases: ['details', 'summary', 'notes'] },
      { field: 'source', type: 'enum', aliases: ['intake_source', 'origin'] },
      { field: 'referral_source', type: 'string', aliases: ['referred_by', 'referral_from'] },
      { field: 'intake_date', type: 'datetime', aliases: ['created_date', 'intake_datetime'] },
      { field: 'opened_date', type: 'datetime', required: true, aliases: ['open_date', 'start_date'] },
      { field: 'closed_date', type: 'datetime', aliases: ['close_date', 'end_date'] },
      { field: 'due_date', type: 'date', aliases: ['target_date'] },
      { field: 'outcome', type: 'enum', aliases: ['result'] },
      { field: 'outcome_notes', type: 'string', aliases: ['result_notes', 'closure_notes'] },
      { field: 'closure_reason', type: 'string', aliases: ['close_reason'] },
      { field: 'requires_followup', type: 'boolean', aliases: ['needs_follow_up'] },
      { field: 'followup_date', type: 'date', aliases: ['follow_up_date'] },
      { field: 'tags', type: 'string', aliases: ['labels', 'segments'] },
    ],
  },
  {
    table: 'follow_ups',
    label: 'Follow Ups',
    aliases: ['follow_up', 'followup', 'reminder', 'checkin'],
    fields: [
      { field: 'follow_up_id', type: 'uuid', aliases: ['id', 'followupid'] },
      { field: 'organization_id', type: 'uuid', aliases: ['account_id', 'organization_account_id'] },
      { field: 'entity_type', type: 'enum', required: true, aliases: ['regarding_type', 'related_type'] },
      { field: 'entity_id', type: 'uuid', required: true, aliases: ['case_id', 'task_id', 'contact_id', 'related_id'] },
      { field: 'title', type: 'string', required: true, aliases: ['subject', 'name'] },
      { field: 'description', type: 'string', aliases: ['details', 'notes'] },
      { field: 'scheduled_date', type: 'date', required: true, aliases: ['date', 'followup_date'] },
      { field: 'scheduled_time', type: 'string', aliases: ['time', 'followup_time'] },
      { field: 'frequency', type: 'enum', aliases: ['cadence', 'repeat'] },
      { field: 'frequency_end_date', type: 'date', aliases: ['repeat_until'] },
      { field: 'method', type: 'enum', aliases: ['channel', 'contact_method'] },
      { field: 'status', type: 'enum', aliases: ['state'] },
      { field: 'completed_date', type: 'datetime', aliases: ['completion_date'] },
      { field: 'completed_notes', type: 'string', aliases: ['completion_notes', 'outcome_notes'] },
      { field: 'assigned_to', type: 'uuid', aliases: ['assignee_id', 'assigned_user_id'] },
    ],
  },
  {
    table: 'tasks',
    label: 'Tasks',
    aliases: ['task', 'todo', 'action_item', 'work_item'],
    fields: [
      { field: 'task_id', type: 'uuid', aliases: ['id', 'taskid'] },
      { field: 'title', type: 'string', required: true, aliases: ['subject', 'name'] },
      { field: 'description', type: 'string', aliases: ['details', 'notes'] },
      { field: 'status', type: 'enum', aliases: ['state'] },
      { field: 'priority', type: 'enum', aliases: ['urgency'] },
      { field: 'assigned_to', type: 'uuid', aliases: ['assignee_id', 'assigned_user_id'] },
      { field: 'due_date', type: 'datetime', aliases: ['deadline'] },
      { field: 'start_date', type: 'datetime', aliases: ['scheduled_start'] },
      { field: 'completed_date', type: 'datetime', aliases: ['completion_date'] },
      { field: 'related_contact_id', type: 'uuid', aliases: ['contact_id'] },
      { field: 'related_case_id', type: 'uuid', aliases: ['case_id'] },
      { field: 'tags', type: 'string', aliases: ['labels', 'segments'] },
    ],
  },
];
